export default {
    FIRESTORE_INSERT_START:'FIRESTORE_INSERT_START',
    FIRESTORE_INSERT_SUCCESS:'FIRESTORE_INSERT_SUCCESS',
    FIRESTORE_INSERT_ERROR:'FIRESTORE_INSERT_ERROR',
    FIRESTORE_SELECT_START:'FIRESTORE_SELECT_START',
    FIRESTORE_SELECT_SUCCESS:'FIRESTORE_SELECT_SUCCESS',
    FIRESTORE_SELECT_ERROR:'FIRESTORE_SELECT_ERROR',
}