export default {
    SUBSCRIPTION_LOAD_START:'SUBSCRIPTION_LOAD_START',
    SUBSCRIPTION_LOAD_SUCCESS:'SUBSCRIPTION_LOAD_SUCCESS',
    SUBSCRIPTION_LOAD_ERROR:'SUBSCRIPTION_LOAD_ERROR',
    SUBSCRIPTION_CREATE_START:'SUBSCRIPTION_CREATE_START',
    SUBSCRIPTION_CREATE_SUCCESS:'SUBSCRIPTION_CREATE_SUCCESS',
    SUBSCRIPTION_CREATE_ERROR:'SUBSCRIPTION_CREATE_ERROR',
    SUBSCRIPTION_DELETE_START:'SUBSCRIPTION_DELETE_START',
    SUBSCRIPTION_DELETE_SUCCESS:'SUBSCRIPTION_DELETE_SUCCESS',
    SUBSCRIPTION_DELETE_ERROR:'SUBSCRIPTION_DELETE_ERROR'
}