export default {
    USER_LOGIN_START:'USER_LOGIN_START',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_ERROR:'USER_LOGIN_ERROR',
    USER_CHECK_START:'USER_CHECK_START',
    USER_CHECK_SUCCESS:'USER_CHECK_SUCCESS',
    USER_CHECK_ERROR:'USER_CHECK_ERROR',
    USER_LOGOUT_START:'USER_LOGOUT_START',
    USER_LOGOUT_SUCCESS:'USER_LOGOUT_SUCCESS',
    USER_UPDATE_START:'USER_UPDATE_START',
    USER_UPDATE_SUCCESS:'USER_UPDATE_SUCCESS',
    USER_UPDATE_ERROR:'USER_UPDATE_ERROR',
    USER_REGISTER_START:'USER_REGISTER_START',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_ERROR:'USER_REGISTER_ERROR',
    SHOPPING_CART_ADD:'SHOPPING_CART_ADD',
    SHOPPING_CART_REMOVE:'SHOPPING_CART_REMOVE'
}