export default {
    CONFIG_LOAD_START: 'CONFIG_LOAD_START',
    CONFIG_LOAD_SUCCESS:'CONFIG_LOAD_SUCCESS',
    CONFIG_LOAD_ERROR:'CONFIG_LOAD_ERROR',
    FILE_UPLOAD_START:'FILE_UPLOAD_START',
    FILE_UPLOAD_SUCCESS:'FILE_UPLOAD_SUCCESS',
    FILE_UPLOAD_ERROR:'FILE_UPLOAD_ERROR'
}